name: Android CI

on:
  push:
    branches:
      - '**'       # run on all branches
  pull_request:
    branches:
      - main       # PRs targeting main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Execute Permission
        run: chmod +x gradlew

      # Running quality checks first
      - name: Run Android Lint
        if: github.ref == 'refs/heads/main'
        run: ./gradlew lint

      - name: Run Detekt
        run: ./gradlew detekt

      # Upload reports
      - name: Upload Detekt Report
        uses: actions/upload-artifact@v4
        with:
          name: detekt-report
          path: build/reports/problems/problems-report.html

      - name: Upload Lint Report
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html

      # Single efficient build step
      - name: Build Project
        run: ./gradlew build

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Assemble Debug APK
        if: github.ref == 'refs/heads/main'
        run: ./gradlew assembleDebug

      # Upload APK
      - name: Upload APK
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk